### ISSUE TITLE
Изменить шапку сайта на морде (баннер)

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#1]

**Comment by ddrozdik** [comment]
@pselfin вижу что уже поменяли. можно закрывать или что-то еще имелось ввиду?

**Comment by pselfin** [comment]
Можно. Пойдет и старая картинка. Не самое критичное

20 нояб. 2017 г. 20:58 пользователь "Dmitry Drozdik" <
notifications@github.com> написал:
