### ISSUE TITLE
Прессвол и х-стенд (ближе к мероприятию)

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#10]
-Прессвол с логотипами организаторов и спонсоров
-Х-стенды с логотипами и т.д.

**Comment by ddrozdik** [comment]
@pselfin а кто делал прошлый раз? есть исходники?

**Comment by pselfin** [comment]
https://yadi.sk/d/v71NX0493PtByA - вот здесь все что было.
По сути пока еще не понятно со спонсорами и тд, так что пока не актуальная задача.
