### ISSUE TITLE
КОФЕ БРЕЙК

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#20]
- -чай
- -кофе
- -печеньки/конфеты
- -сахар
- -стаканчики
- -ложечки
- -тарелочки
- -кулеры и вода (уточнить у колледжа)
- -мусорные пакеты
- + что еще там нужно

**Comment by ArmGono** [comment]
Так же нужна вода в бутылках (маленьких) для спикеров.

**Comment by ArmGono** [comment]
Сегодня был в МЕТРО, выписал все цены. Ниже примерная смета на кофебрейк. 
Прошу внести корректировки если где-то ошибся в кол-ве/рассчетах или что-то забыл

Наименование | Единица | Цена (руб) | Необходимое кол-во | Стоимость (руб)
---------------- | --------- | ----- | ---------------------------- | ----------- 
\* Стаканы  (Картон/пластмассовые чашки) | 50шт | 215/115 | 250шт  | 860 / 460
\** Крышки для стаканов  | 100шт | 185  | 100шт | 185
Тарелки | 50шт | 80 | 150шт | 240
Ложки | 100шт | 65 | 200шт | 130
\** Размешиватели | 1000шт | 200 | 200шт | 200
Мусорные пакеты | 30шт | 20 | 30шт | 20
Бумажные полотенца | 2рулона | 20 | 2рул. | 20
Салфетки | 100 шт | 16 | 200 | 32
\* Вода в бутылках(0.5л) кубай / горячий ключ / св.источник / АРО | 12бут | 204 / 144 / 264 / 132 |  24бут | 408 / 288 / 528 / 164
\* Чай Майский / Липтон / Лисма | 25пак | 43/73/33 | 100пак | 172 / 292 / 132
\* Кофе 3 в 1 (Нескафе / МакКофе / АРО)  | 100 шт | 650 / 873 / 590 | 100шт | 650 / 873 / 590
Кофе обычный (Эльгрессо как на прошлом кемпе) | 100шт  | 538 | 100шт | 538
Сахар(5гр) | 500шт | 425 | 500шт | 425
Печеники | 1 уп  | 40  | 5 уп | 120
Вафли ассорти | 1 уп | 170 | 4 уп | 680

Итого получается примерно на сумму от **4000** до **5000** руб

\* -  Указаны несколько вариантов на обсуждение, цены указаны в том же порядке, в каком перечислены варианты.
\** - Не уверен что нужно

_p.s. в поле единица указано минимальное количество, которое можно купить._

**Comment by pselfin** [comment]
Вышло на 6600 печенек и тд
Кулеры - 3шт по 900
Вода для кулеро - 700 
если не напутал
