### ISSUE TITLE
Бэйджи на сайт (conference/materials):

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#3]
Бэйджи (http://2017.drupalyug.ru/conference/materials):
-изменить год 2016-на-2017
-изменить цвет или сделать заливку-полоски, кружочки, друпликоны... В общем обновить. И это бы как то для всего дизайна применить (сертификаты, элементы и тд)

**Comment by ddrozdik** [comment]
@pselfin что ты имеешь ввиду под изменить цвет, заливку, ты хочешь сделать новую расцветку? просто текущие цвета подобраны под названия спонсорских пакетов.

**Comment by pselfin** [comment]
@ddrozdik ну как то немного обновить дизайн. Может полоски добавить (из оттенков), или какой нибудь паттерн. Типа так https://t6.rbxcdn.com/c814f1e8f8a06de2c63b3b48bf9fb7ff (но не такие цвета конечно).
Вот грубо сделал. что то в этом роде, уже отличается
![badge11](https://user-images.githubusercontent.com/20221773/33060345-fbe855e2-cea8-11e7-841d-37c868a32f37.png)
![badge11-2](https://user-images.githubusercontent.com/20221773/33060445-4ea4c7f2-cea9-11e7-9d61-b9c2c9bb5009.png)

**Comment by ddrozdik** [comment]
Готово, все бейджи на сайте.

**Comment by pselfin** [comment]
**Второй спонсор** что то с ним не так, может битая ссылка?

**Comment by ddrozdik** [comment]
@pselfin поправил, не знаю что было :)
