### ISSUE TITLE
Анонс на https://www.drupical.com/

### ISSUE THREAD

**Issue by ddrozdik** [drupal-russia/Drupalcamp-Krasnodar-2017#33]

**Comment by ddrozdik** [comment]
@pselfin готово?

**Comment by pselfin** [comment]
Вроде должно из групс.рашия подтянуть, подождем денек пока крон сработает

**Comment by pselfin** [comment]
![drupicsl2017](https://user-images.githubusercontent.com/20221773/33552956-c90f89ce-d907-11e7-8362-2304b1e05e18.png)
