### ISSUE TITLE
СЕРТИФИКАТЫ А4

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#4]
СЕРТИФИКАТЫ
-изменить год
-изменить цвет или сделать заливку-полоски, кружочки, друпликоны... В общем обновить. И это бы как то для всего дизайна применить (сертификаты, элементы и тд)

## Сертификаты (именные)

- докладчикам
- организаторам
- индивидуальным спонсорам

**Comment by ddrozdik** [comment]
@pselfin аналогично как здесь https://github.com/drupal-russia/Drupalcamp-Krasnodar-2017/issues/3

**Comment by pselfin** [comment]
отписался в #3 
С сертификатами сложнее конечно.. Там такая интересная структура. 
Если получится что нибудь придумать - гуд. Если нет- то будем старые шаблоны использовать...
Про шаблон презентации аналогично

**Comment by ddrozdik** [comment]
@pselfin держи файлик с вариантами, можешь выбрать какой использовать для печати. 
[sertifikat.eps.zip](https://github.com/drupal-russia/Drupalcamp-Krasnodar-2017/files/1522800/sertifikat.eps.zip)

**Comment by ddrozdik** [comment]
[sertifikat.eps 2.zip](https://github.com/drupal-russia/Drupalcamp-Krasnodar-2017/files/1540670/sertifikat.eps.2.zip)

@pselfin ждем комментариев :)

**Comment by pselfin** [comment]
@ddrozdik  огонь!!!
Даже получилось 4 варианта, оставил ярко зеленый для индивидуальных спонсоров.
вообще супер!
