### ISSUE TITLE
СЕРТИФИКАТЫ СПОНСОРОВ

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#6]
Вариант примерно как в прошлом году: металл на деревянной основе
-либо в другом месте будем делать, чтобы отличались
-и можно изменить оформление

**Comment by ddrozdik** [comment]
@pselfin я так понимаю это не к Жене. да?

**Comment by pselfin** [comment]
Да, там по факту делали простое. Пока не обращать внимание)
