### ISSUE TITLE
Баннеры для соцсетей на основе картинки для главной страницы сайта

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#7]
В прошлом году для новостей делали http://2016.drupalyug.ru/conference/news
в целом это и я могу сделать, главное баннер сделать для главной страницы)

**Comment by ddrozdik** [comment]
@pselfin напомни пожалуйста какой банер нужно

**Comment by pselfin** [comment]
Это на основе прошлогодних уже делаю, так что можно тикет закрыть, не самая
острая задача

20 нояб. 2017 г. 20:47 пользователь "Dmitry Drozdik" <
notifications@github.com> написал:
