### ISSUE TITLE
Шаблон презентации

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#8]
Делали в гугл доках, норм практика
-обновить дизайна шаблона в соответствии с цветами, заливками и тд, что будет везде использоваться

**Comment by ddrozdik** [comment]
Петя не помнишь где старая презентация?

**Comment by pselfin** [comment]
https://docs.google.com/presentation/d/1n1DQt2ec1Z1Oz4SsLF0DiF6muS8O9LNc_iloLmFx_Rc/edit?usp=sharing

**Comment by ddrozdik** [comment]
@pselfin https://docs.google.com/presentation/d/10ykNvkRIofw-v7Pt0cF-xJ2gG77vkngrH3ixp-28QPo/edit#slide=id.p3

Ничего пока не придумали на главную. не знаю стоит ли менять, посмотри скажи свое мнение.

**Comment by pselfin** [comment]
@ddrozdik думаю вполне норм.
