### ISSUE TITLE
Коммерческое предложение спонсорам

### ISSUE THREAD

**Issue by pselfin** [drupal-russia/Drupalcamp-Krasnodar-2017#9]
PDF-ка для рассылки спонсорам.
Обновить информацию, год. 
Тарифы остаются те же самые.
Можно использовать фотографии с прошлого кемпа.

В этот раз будет один день, два потока с докладами и мастер-класс для студентов.

вот здесь кое что есть по информации, можно брать или креативить
[Предложение для колледжа.docx](https://github.com/drupal-russia/Drupalcamp-Krasnodar-2017/files/1469855/default.docx)

**Comment by ddrozdik** [comment]
@pselfin Можешь скинь фото которые можно использовать? Нужна ли англ версия?

**Comment by pselfin** [comment]
Англ версия не нужна, лишний труд.
фото можно брать эти 
https://vk.com/album-84387938_242357844
https://vk.com/album-84387938_242418063
https://vk.com/album-84387938_247565258
если не достаточно, еще поищем.
Вот еще общая https://yadi.sk/i/1Cbapzf93Pt6iT

**Comment by ddrozdik** [comment]
@pselfin вот ссылка на гугл презентацию https://docs.google.com/presentation/d/1Aq46oYKYKD35CvSqTz7mbhm9xzLd-4miJpSC_pFlm38/edit#slide=id.p

Посмотри, расшарил тебе права на редактирование. Можешь поменять если что-то не ок.
